#####         #####           #####        ##############    ###############     ############    #####         #####
 ### ##        ###           #######       ##   ###    ##    ##    ###    ##    ###        ###    ### ##        ###
 ###  ##       ###          ###   ###           ###                ###          ##          ##    ###  ##       ###
 ###    ##     ###         ###     ###          ###                ###          ##          ##    ###    ##     ###
 ###     ##    ###        ###       ###         ###                ###          ##          ##    ###     ##    ###
 ###      ##   ###       ###############        ###                ###          ##          ##    ###      ##   ###
 ###       ##  ###      ###           ###       ###                ###          ##          ##    ###       ##  ###
 ###        ## ###     ###             ###      ###          ##    ###    ##    ###        ###    ###        ## ###
#####         #####   #####           #####     ###          ###############     ############    #####         #####

####################################################################################################################

# ALL THE CONFIGURATION RELATED TO NATIONS PLUGIN MAIN SETTINGS ARE HERE!

# IMPORTANT!
# Some Rules that must be followed while configuring the file!
#   - If a value is in quotes ('' <- These things) Do not Remove them!
#   - Int value must be written in Integer form
#   - Boolean value must be written in Boolean form

####################################################################################################################
#                                          MAIN CONFIGURATION STARTS


